version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
        - "27017:27017" 
    volumes:
        - mongo_data:/data/db
  pokedex_api:
    container_name: pokedex_api_v2
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ConnectionString=mongodb://catalogdb:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false"
    depends_on:
      - catalogdb
    ports:
      - "8006:80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro