version: '3.4'

services:
  catalogdb:
    image: mongo
  pokedex_api:
    image: ${DOCKER_REGISTRY-}pokedexapiv2
    build:
      context: .
      dockerfile: pokedex_api_V2/Dockerfile
volumes:
  mongo_data: